services:
  - type: web
    name: mytrack
    env: ruby # RubyでもNodeでもなんでもOK。無視される。
    buildCommand: "./.render/build.sh"
    startCommand: "php artisan serve --host 0.0.0.0 --port 10000"
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:V8XmKQsgibK56W3EwqiguS75cT6wTehCuc1YuC6frrk=
      - key: APP_URL
        value: https://your-subdomain.onrender.com
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: database/database.sqlite
